trigger:
- main

pool:
  name: Default
  demands:
    - agent.name -equals CRIBL-QAYUMTAH1

steps:
- task: NodeTool@0
  inputs:
    versionSpec: '16.x'  # Ensure this version matches your app's requirements
  displayName: 'Install Node.js'

- script: |
    echo "Cleaning npm cache..."
    npm cache clean --force  # Clear npm cache to avoid any corrupted or stale data
  displayName: 'Clean npm cache'

- script: |
    echo "Verifying npm cache..."
    npm cache verify  # Verify the integrity of npm cache
  displayName: 'Verify npm cache'

- script: |
    echo "Installing dependencies with legacy peer dependencies handling..."
    npm ci --legacy-peer-deps --verbose  # Install exactly from package-lock.json
  displayName: 'Install dependencies'

- script: |
    echo "Building the app..."
    npm run build  # This step should generate the /build folder
  displayName: 'Build the app'

- task: AzureWebApp@1
  inputs:
    azureSubscription: 'MyPortfolio'
    appName: 'NewPortfolioApp'  # Ensure this matches your Azure Web App name
    package: '$(Build.SourcesDirectory)/build'  # Ensure this is the correct path to the build folder
  displayName: 'Deploy to Azure App Service'

- script: |
    echo "Build and deployment pipeline executed successfully!"
  displayName: 'Finalize build'
